generate_sim_data_CAD;
net = FFNN(6,5,[30 30],'activation_fun_str_list',{'tanh','tanh','purelin'});
net = net.setTrainOpt(input_mat(1:6,:), output_mat(2:6,:),...
                'EpochNum',50,...
                'LearningRate',0.5,...
                'FreezeLayer', [],...
                'TrainMethod','BGD',...
                'PenaltyMethod','l1weight');
net.train_opt_struct.miniBatch_ratio = 0.03;
net.train_opt_struct.plot_opt_struct.drawNet.updateRate = 1;
net = net.start_train();   


% 
% generate_sim_data_CAD2
% net2 = FFNN(6,5,[30 30],'activation_fun_str_list',{'tanh','tanh','purelin'});
% net2.net.Weight_layers(1:2) = net.net.Weight_layers(1:2);
% net2.net.Bias_Layers(1:2) = net.net.Bias_Layers(1:2);
% net2 = net2.setTrainOpt(input_mat(1:6,:), output_mat(2:6,:),...
%                 'EpochNum',50,...
%                 'LearningRate',0.4,...
%                 'FreezeLayer', [1,2],...
%                 'TrainMethod','BGD',...
%                 'PenaltyMethod','l1weight');
% net2.train_opt_struct.miniBatch_ratio = 0.06;
% net2 = net2.start_train();   
%           

